package com.cqutcm.biomed.service;
import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.util.*;
@Service public class ImprovementRecommendationService{
 private final JdbcTemplate jdbc;private final PermissionService permissions;public ImprovementRecommendationService(JdbcTemplate j,PermissionService p){jdbc=j;permissions=p;}
 @Transactional public List<Map<String,Object>> list(String evaluationId,PermissionService.Actor actor){professional(actor);List<Map<String,Object>> details=jdbc.queryForList("SELECT d.*,e.batch_id,e.evaluation_record_id,e.evaluator_name,b.responsible_person FROM multi_metric_evaluation_detail d JOIN multi_metric_evaluation e ON e.id=d.evaluation_id JOIN herb_batch b ON b.id=e.batch_id WHERE d.evaluation_id=? AND (d.judgement<>'qualified' OR d.raw_score<80)",evaluationId);for(Map<String,Object>d:details){if(jdbc.queryForObject("SELECT COUNT(*) FROM improvement_recommendation WHERE evaluation_detail_id=?",Integer.class,d.get("id"))==0)generate(evaluationId,d);}return jdbc.queryForList("SELECT r.id,r.multi_evaluation_id AS multiEvaluationId,r.metric_code AS metricCode,r.issue_title AS issueTitle,r.issue_description AS issueDescription,r.severity,r.improvement_target AS improvementTarget,r.recommended_material_id AS recommendedMaterialId,m.title AS materialTitle,r.recommendation_reason AS recommendationReason,r.status,r.created_issue_id AS createdIssueId FROM improvement_recommendation r LEFT JOIN training_material m ON m.id=r.recommended_material_id WHERE r.multi_evaluation_id=? ORDER BY r.generated_at",evaluationId);}
 private void generate(String evaluationId,Map<String,Object>d){String code=String.valueOf(d.get("metric_code"));List<Map<String,Object>>materials=jdbc.queryForList("SELECT t.training_material_id,m.title FROM training_material_tag t JOIN training_material m ON m.id=t.training_material_id WHERE t.metric_code=? AND m.status IN ('已发布','published') ORDER BY t.priority_value DESC LIMIT 1",code);Object material=materials.isEmpty()?null:materials.get(0).get("training_material_id");String metric=String.valueOf(d.get("metric_name")),judgement=String.valueOf(d.get("judgement"));String severity=((Number)d.get("raw_score")).doubleValue()<60?"high":"medium";String target="将"+metric+"恢复到标准范围并在复评中达到80分以上";jdbc.update("INSERT INTO improvement_recommendation(id,multi_evaluation_id,evaluation_detail_id,metric_code,issue_title,issue_description,severity,improvement_target,recommended_material_id,recommendation_reason) VALUES(?,?,?,?,?,?,?,?,?,?)",UUID.randomUUID().toString(),evaluationId,d.get("id"),code,metric+"异常整改",metric+"实测值为"+d.get("measured_value")+d.get("unit_name")+"，判定为"+judgement,severity,target,material,material==null?"暂无完全匹配的已发布素材":"按指标标签和素材优先级自动匹配");}
 @Transactional public Map<String,Object> accept(String id,Map<String,Object>body,PermissionService.Actor actor){professional(actor);Map<String,Object>r=required("SELECT r.*,e.batch_id,e.evaluation_record_id,e.evaluator_name,b.responsible_person FROM improvement_recommendation r JOIN multi_metric_evaluation e ON e.id=r.multi_evaluation_id JOIN herb_batch b ON b.id=e.batch_id WHERE r.id=?",id);if(!"pending".equals(r.get("status")))throw new IllegalArgumentException("recommendation has already been handled");String issueId=UUID.randomUUID().toString();jdbc.update("INSERT INTO evaluation_issue(id,evaluation_id,batch_id,title,description,severity,improvement_target,status,creator_name) VALUES(?,?,?,?,?,?,?,?,?)",issueId,r.get("evaluation_record_id"),r.get("batch_id"),r.get("issue_title"),r.get("issue_description"),r.get("severity"),r.get("improvement_target"),"open",actor.name());if(r.get("recommended_material_id")!=null){String assignee=String.valueOf(body.getOrDefault("assignee",r.get("responsible_person")!=null?r.get("responsible_person"):r.get("evaluator_name")));jdbc.update("INSERT INTO improvement_training_task(id,issue_id,training_material_id,title,assignee_name,status,creator_name) VALUES(?,?,?,?,?,'pending',?)",UUID.randomUUID().toString(),issueId,r.get("recommended_material_id"),r.get("issue_title")+"专项培训",assignee,actor.name());jdbc.update("UPDATE evaluation_issue SET status='training' WHERE id=?",issueId);}jdbc.update("UPDATE improvement_recommendation SET status='accepted',created_issue_id=?,handled_by=?,handled_at=NOW() WHERE id=?",issueId,actor.name(),id);return Map.of("issueId",issueId,"message","recommendation accepted");}
 @Transactional public void ignore(String id,PermissionService.Actor actor){professional(actor);jdbc.update("UPDATE improvement_recommendation SET status='ignored',handled_by=?,handled_at=NOW() WHERE id=? AND status='pending'",actor.name(),id);}
 private void professional(PermissionService.Actor a){if(permissions.isStudent(a))throw new AuthorizationDeniedException("students cannot handle improvement recommendations");}private Map<String,Object>required(String sql,Object...args){List<Map<String,Object>>r=jdbc.queryForList(sql,args);if(r.isEmpty())throw new IllegalArgumentException("recommendation not found");return r.get(0);}
}
