package com.cqutcm.biomed.service;
import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;import java.nio.charset.StandardCharsets;import java.security.*;import java.time.*;import java.util.*;
@Service public class MobileCollectionService{
 private final JdbcTemplate jdbc;private final PermissionService permissions;private final SecureRandom random=new SecureRandom();
 public MobileCollectionService(JdbcTemplate j,PermissionService p){jdbc=j;permissions=p;}
 public List<Map<String,Object>> devices(PermissionService.Actor actor){if(!permissions.isAdmin(actor))throw new AuthorizationDeniedException("only admin can manage collection devices");return jdbc.queryForList("SELECT d.id,d.device_code AS deviceCode,d.device_name AS deviceName,d.owner_name AS owner,d.platform_name AS platform,d.status,d.last_seen_at AS lastSeenAt,d.created_at AS createdAt,(SELECT COUNT(*) FROM mobile_sync_record s WHERE s.device_id=d.id AND s.sync_status='accepted') AS acceptedCount,(SELECT COUNT(*) FROM mobile_sync_record s WHERE s.device_id=d.id AND s.sync_status='rejected') AS rejectedCount FROM mobile_collection_device d ORDER BY d.created_at DESC");}
 @Transactional public Map<String,Object> register(Map<String,Object>b,PermissionService.Actor actor){if(!permissions.isAdmin(actor))throw new AuthorizationDeniedException("only admin can register devices");String code=req(b,"deviceCode"),name=req(b,"deviceName"),token=newToken(),id=UUID.randomUUID().toString();jdbc.update("INSERT INTO mobile_collection_device(id,device_code,device_name,owner_name,platform_name,token_hash,created_by) VALUES(?,?,?,?,?,?,?)",id,code,name,opt(b,"owner"),opt(b,"platform"),hash(token),actor.name());return Map.of("id",id,"deviceCode",code,"deviceName",name,"token",token,"warning","token is shown only once");}
 @Transactional public Map<String,Object> rotate(String id,PermissionService.Actor actor){if(!permissions.isAdmin(actor))throw new AuthorizationDeniedException("only admin can rotate tokens");String token=newToken();if(jdbc.update("UPDATE mobile_collection_device SET token_hash=?,token_rotated_at=NOW(),updated_at=NOW() WHERE id=?",hash(token),id)==0)throw new IllegalArgumentException("device not found");return Map.of("token",token,"warning","token is shown only once");}
 @Transactional public void setStatus(String id,String status,PermissionService.Actor actor){if(!permissions.isAdmin(actor))throw new AuthorizationDeniedException("only admin can change device status");if(!List.of("active","disabled").contains(status))throw new IllegalArgumentException("invalid device status");jdbc.update("UPDATE mobile_collection_device SET status=?,updated_at=NOW() WHERE id=?",status,id);}
 public Map<String,Object> syncStatus(String token){Map<String,Object>d=device(token);return Map.of("deviceCode",d.get("device_code"),"accepted",jdbc.queryForObject("SELECT COUNT(*) FROM mobile_sync_record WHERE device_id=? AND sync_status='accepted'",Integer.class,d.get("id")),"rejected",jdbc.queryForObject("SELECT COUNT(*) FROM mobile_sync_record WHERE device_id=? AND sync_status='rejected'",Integer.class,d.get("id")),"lastSeenAt",String.valueOf(d.get("last_seen_at")));}
 @Transactional public Map<String,Object> ingest(String token,List<Map<String,Object>>records){Map<String,Object>d=device(token);if(records==null||records.isEmpty())throw new IllegalArgumentException("records are required");if(records.size()>200)throw new IllegalArgumentException("at most 200 records per request");List<Map<String,Object>>results=new ArrayList<>();int accepted=0,duplicate=0,rejected=0;for(Map<String,Object>r:records){String client=String.valueOf(r.getOrDefault("clientRecordId","")).trim();if(client.isBlank()){results.add(result("","rejected","clientRecordId is required"));rejected++;continue;}List<Map<String,Object>>old=jdbc.queryForList("SELECT growth_record_id FROM mobile_sync_record WHERE device_id=? AND client_record_id=?",d.get("id"),client);if(!old.isEmpty()){results.add(result(client,"duplicate",String.valueOf(old.get(0).get("growth_record_id"))));duplicate++;continue;}try{String growthId=insertGrowth(d,r,client);jdbc.update("INSERT INTO mobile_sync_record(id,device_id,client_record_id,growth_record_id,sync_status) VALUES(?,?,?,?, 'accepted')",UUID.randomUUID().toString(),d.get("id"),client,growthId);results.add(result(client,"accepted",growthId));accepted++;}catch(Exception ex){jdbc.update("INSERT INTO mobile_sync_record(id,device_id,client_record_id,sync_status,error_message) VALUES(?,?,?,'rejected',?)",UUID.randomUUID().toString(),d.get("id"),client,ex.getMessage());results.add(result(client,"rejected",ex.getMessage()));rejected++;}}jdbc.update("UPDATE mobile_collection_device SET last_seen_at=NOW(),updated_at=NOW() WHERE id=?",d.get("id"));return Map.of("accepted",accepted,"duplicates",duplicate,"rejected",rejected,"items",results);}
 private String insertGrowth(Map<String,Object>d,Map<String,Object>r,String client){String batchId=req(r,"batchId");Map<String,Object>b=one("SELECT b.id,h.name AS herb_name,b.district FROM herb_batch b JOIN herb h ON h.id=b.herb_id WHERE b.id=? AND b.status='active'",batchId);BigDecimal lat=num(r,"latitude"),lng=num(r,"longitude"),accuracy=num(r,"locationAccuracy");if((lat==null)!=(lng==null))throw new IllegalArgumentException("longitude and latitude must be provided together");if(lat!=null&&(lat.compareTo(BigDecimal.valueOf(-90))<0||lat.compareTo(BigDecimal.valueOf(90))>0))throw new IllegalArgumentException("invalid latitude");if(lng!=null&&(lng.compareTo(BigDecimal.valueOf(-180))<0||lng.compareTo(BigDecimal.valueOf(180))>0))throw new IllegalArgumentException("invalid longitude");String id=UUID.randomUUID().toString();jdbc.update("INSERT INTO growth_record(id,batch_id,herb_name,district,temperature,humidity,soil_ph,growth_stage,collect_source,recorder_name,recorder_role,recorded_at,longitude,latitude,location_accuracy,device_id,client_record_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW())",id,batchId,b.get("herb_name"),b.get("district"),num(r,"temperature"),num(r,"humidity"),num(r,"soilPh"),opt(r,"growthStage"),"mobile_app",d.get("owner_name"),"device",LocalDateTime.parse(req(r,"recordedAt")),lng,lat,accuracy,d.get("id"),client);return id;}
 private Map<String,Object>device(String token){if(token==null||token.isBlank())throw new AuthenticationRequiredException("device token required");List<Map<String,Object>>r=jdbc.queryForList("SELECT * FROM mobile_collection_device WHERE token_hash=?",hash(token.trim()));if(r.isEmpty())throw new AuthenticationRequiredException("invalid device token");if(!"active".equals(r.get(0).get("status")))throw new AuthorizationDeniedException("device is disabled");return r.get(0);}private String newToken(){byte[]b=new byte[32];random.nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);}private String hash(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}private String req(Map<String,Object>b,String k){String v=String.valueOf(b.getOrDefault(k,"")).trim();if(v.isBlank())throw new IllegalArgumentException(k+" is required");return v;}private Object opt(Map<String,Object>b,String k){String v=String.valueOf(b.getOrDefault(k,"")).trim();return v.isBlank()?null:v;}private BigDecimal num(Map<String,Object>b,String k){Object v=b.get(k);return v==null||String.valueOf(v).isBlank()?null:new BigDecimal(String.valueOf(v));}private Map<String,Object>one(String q,Object...a){List<Map<String,Object>>r=jdbc.queryForList(q,a);if(r.isEmpty())throw new IllegalArgumentException("batch not found");return r.get(0);}private Map<String,Object>result(String c,String s,String detail){return Map.of("clientRecordId",c,"status",s,"detail",detail==null?"":detail);}
}
