<script setup>
import{inject,onMounted,reactive,ref}from"vue";import{KeyRound,Plus,RefreshCw,Smartphone}from"lucide-vue-next";import{api}from"@/services/api";import AppSelect from"@/components/AppSelect.vue";
const notify=inject("notify"),loading=ref(true),devices=ref([]),tokenResult=ref(null),form=reactive({deviceCode:"",deviceName:"",owner:"",platform:"Android"});
const platformOptions=["Android","iOS","Sensor"].map(value=>({value,label:value}));
async function load(){loading.value=true;try{devices.value=(await api("/api/mobile/devices")).items||[]}catch(e){notify(e.message)}finally{loading.value=false}}
async function register(){try{tokenResult.value=await api("/api/mobile/devices",{method:"POST",body:JSON.stringify(form)});notify("设备已登记，请立即保存令牌");Object.assign(form,{deviceCode:"",deviceName:"",owner:"",platform:"Android"});await load()}catch(e){notify(e.message)}}
async function rotate(d){if(!window.confirm("轮换后旧令牌立即失效，确认继续？"))return;try{tokenResult.value=await api(`/api/mobile/devices/${d.id}/rotate-token`,{method:"POST"});notify("令牌已轮换") }catch(e){notify(e.message)}}
async function toggle(d){try{await api(`/api/mobile/devices/${d.id}/status`,{method:"PUT",body:JSON.stringify({status:d.status==='active'?'disabled':'active'})});await load()}catch(e){notify(e.message)}}
onMounted(load);
</script>
<template><section class="device-page"><form class="device-register" @submit.prevent="register"><div><Smartphone :size="21"/><span><h2>登记采集终端</h2><p>设备令牌仅显示一次，数据库不保存明文。</p></span></div><input v-model="form.deviceCode" required placeholder="设备编号，如 APP-001"/><input v-model="form.deviceName" required placeholder="设备名称"/><input v-model="form.owner" placeholder="负责人"/><AppSelect v-model="form.platform" :options="platformOptions" aria-label="选择设备平台"/><button><Plus :size="15"/>登记</button></form><div v-if="tokenResult" class="device-token"><KeyRound :size="18"/><div><strong>设备令牌（仅本次显示）</strong><code>{{tokenResult.token}}</code></div><button class="button-secondary" @click="tokenResult=null">我已保存</button></div><div class="device-list"><header><h3>设备与同步状态</h3><button class="button-secondary" @click="load"><RefreshCw :size="15"/>刷新</button></header><div v-if="loading" class="empty-state">正在加载...</div><table v-else><thead><tr><th>设备</th><th>负责人</th><th>平台</th><th>状态</th><th>成功/失败</th><th>最后在线</th><th></th></tr></thead><tbody><tr v-for="d in devices" :key="d.id"><td>{{d.deviceName}}<small>{{d.deviceCode}}</small></td><td>{{d.owner||'-'}}</td><td>{{d.platform||'-'}}</td><td>{{d.status==='active'?'启用':'禁用'}}</td><td>{{d.acceptedCount}} / {{d.rejectedCount}}</td><td>{{d.lastSeenAt||'从未'}}</td><td><button class="button-secondary" @click="rotate(d)">轮换令牌</button><button class="button-secondary" @click="toggle(d)">{{d.status==='active'?'禁用':'启用'}}</button></td></tr></tbody></table></div></section></template>
