<script setup>
import{computed,inject,onMounted,ref}from"vue";import{ClipboardCheck,ExternalLink,RefreshCw}from"lucide-vue-next";import{useRouter}from"vue-router";import{api}from"@/services/api";import AppSelect from"@/components/AppSelect.vue";
const notify=inject("notify"),role=inject("currentRole"),router=useRouter(),loading=ref(true),schemeId=ref(""),batchId=ref(""),data=ref({schemes:[],batches:[],evaluations:[]}),selected=ref(null),recommendations=ref([]);
const currentScheme=computed(()=>data.value.schemes.find(x=>x.id===schemeId.value));
const schemeOptions=computed(()=>data.value.schemes.map(s=>({value:s.id,label:`${s.schemeName} · V${s.versionNo}`})));
const batchOptions=computed(()=>data.value.batches.map(b=>({value:b.id,label:`${b.batchCode} · ${b.batchName}`})));
async function load(){loading.value=true;try{data.value=await api("/api/multi-evaluations");schemeId.value||=data.value.schemes[0]?.id||"";batchId.value||=data.value.batches[0]?.id||""}catch(e){notify(e.message)}finally{loading.value=false}}
async function evaluate(){try{selected.value=await api("/api/multi-evaluations/evaluate",{method:"POST",body:JSON.stringify({schemeId:schemeId.value,batchId:batchId.value})});await loadRecommendations(selected.value.evaluation.id);notify("自动评价已生成，并同步到评价体系");await load()}catch(e){notify(e.message)}}
async function detail(id){try{selected.value=await api(`/api/multi-evaluations/${id}`);await loadRecommendations(id)}catch(e){notify(e.message)}}
async function loadRecommendations(id){const r=await api(`/api/improvement-recommendations/evaluation/${id}`);recommendations.value=r.items||[]}
async function acceptRecommendation(r){const assignee=window.prompt("请输入培训任务负责人（没有匹配素材时仅创建问题）","")||"";try{await api(`/api/improvement-recommendations/${r.id}/accept`,{method:"POST",body:JSON.stringify({assignee})});notify("整改问题和推荐培训任务已创建");await loadRecommendations(r.multiEvaluationId)}catch(e){notify(e.message)}}
async function ignoreRecommendation(r){try{await api(`/api/improvement-recommendations/${r.id}/ignore`,{method:"PUT"});notify("建议已忽略");await loadRecommendations(r.multiEvaluationId)}catch(e){notify(e.message)}}
async function removeEvaluation(id){if(!window.confirm("确认删除这条自动评价及其评分明细？"))return;try{await api(`/api/multi-evaluations/${id}`,{method:"DELETE"});if(selected.value?.evaluation?.id===id)selected.value=null;notify("自动评价已删除");await load()}catch(e){notify(e.message)}}
function text(v){return({qualified:"合格",unqualified:"不合格",excellent:"优秀",good:"良好",below_standard:"低于标准",above_standard:"高于标准"})[v]||v}
onMounted(load);
</script>
<template><section class="auto-evaluation-page"><div class="auto-eval-command"><div><ClipboardCheck :size="22"/><span><h2>批次多指标评价</h2><p>评分明细保留指标标准版本和原始数据来源。</p></span></div><AppSelect v-model="schemeId" :options="schemeOptions" aria-label="选择评价方案"/><AppSelect v-model="batchId" :options="batchOptions" aria-label="选择药材批次"/><button :disabled="!schemeId||!batchId" @click="evaluate">执行自动评价</button><small v-if="currentScheme">合格线 {{currentScheme.passingScore}} 分 · {{currentScheme.itemCount}} 项指标</small></div>
<div v-if="selected" class="auto-eval-result"><header><div><span>综合得分</span><strong>{{selected.evaluation.total_score}}</strong></div><div><span>评价等级</span><strong>{{text(selected.evaluation.grade_name)}}</strong></div><div><span>评价结果</span><strong>{{text(selected.evaluation.result)}}</strong></div><button v-if="selected.evaluation.result==='unqualified'" @click="router.push('/improvement')"><ExternalLink :size="15"/>进入改进闭环</button></header><table><thead><tr><th>指标</th><th>实测值</th><th>原始分</th><th>权重</th><th>加权分</th><th>来源数</th></tr></thead><tbody><tr v-for="d in selected.details" :key="d.metricName"><td>{{d.metricName}}<small>标准 V{{d.metricVersion}}</small></td><td>{{d.measuredValue}} {{d.unitName}}</td><td>{{d.rawScore}}</td><td>{{d.weightValue}}%</td><td>{{d.weightedScore}}</td><td>{{d.sourceCount}}</td></tr></tbody></table><section v-if="recommendations.length" class="recommendation-list"><h3>异常指标改进建议</h3><article v-for="r in recommendations" :key="r.id"><div><strong>{{r.issueTitle}}</strong><p>{{r.issueDescription}}</p><small>目标：{{r.improvementTarget}}</small></div><div><span>推荐素材：{{r.materialTitle||'暂无匹配素材'}}</span><small>{{r.recommendationReason}}</small></div><div v-if="r.status==='pending'"><button @click="acceptRecommendation(r)">采纳并创建任务</button><button class="button-secondary" @click="ignoreRecommendation(r)">忽略</button></div><b v-else>{{r.status==='accepted'?'已采纳':'已忽略'}}</b></article></section></div>
<div class="auto-eval-history"><header><h3>评价历史</h3><button class="button-secondary" @click="load"><RefreshCw :size="15"/>刷新</button></header><div v-if="loading" class="empty-state">正在加载...</div><table v-else><thead><tr><th>批次</th><th>方案</th><th>总分</th><th>等级</th><th>结果</th><th>评价人</th><th></th></tr></thead><tbody><tr v-for="e in data.evaluations" :key="e.id"><td>{{e.batchName}}</td><td>{{e.schemeName}}</td><td>{{e.totalScore}}</td><td>{{text(e.gradeName)}}</td><td>{{text(e.result)}}</td><td>{{e.evaluator}}</td><td class="auto-eval-actions"><button class="button-secondary" @click="detail(e.id)">查看明细</button><button v-if="role==='admin'" class="button-danger" @click="removeEvaluation(e.id)">删除</button></td></tr></tbody></table></div></section></template>
